### ISSUE TITLE
Should Publish should take a context?

### ISSUE THREAD

**Issue by jessekv** [twpayne/go-pubsub#1]
`Publish`  blocks, and can hang if you are trying to terminate the process.

I'd propose something like the following:

```go
// Publish publishes value to all subscribers.
func (t *Topic[T]) Publish(ctx context.Context, value T) error {
	select {
	case <-ctx.Done():
		return errors.New("Publish was cancelled")
	case t.publishCh <- value:
		return nil
	}
}
```

**Comment by twpayne** [comment]
Good point. I agree. Please create a PR.

When the context is done, rather than returning `errors.New("Publish was cancelled")`, return [`context.Cause(ctx)`](https://pkg.go.dev/context#Cause).

**Comment by twpayne** [comment]
I suspect that `Subscribe` and `Unsubscribe` should also take a context.

**Comment by jessekv** [comment]
Here's the PR: https://github.com/twpayne/go-pubsub/pull/2

**Comment by jessekv** [comment]
I agree about `Subscribe` and `Unsubscribe`, they can also be blocked for the same reason.

**Comment by jessekv** [comment]
Does it make sense to handle the context from `NewTopic` separately?

**Comment by twpayne** [comment]
> Does it make sense to handle the context from `NewTopic` separately?

Yes, for two reasons:

Firstly, `NewTopic`, `Publish`, and `Subscribe` will typically be called from different goroutines running in different contexts.

Secondly, the [context documentation](https://pkg.go.dev/context) states explicitly:

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

**Comment by jessekv** [comment]
Thanks! This makes perfect sense.

**Comment by twpayne** [comment]
Thanks for the issue, PR, and discussion :)

**Comment by twpayne** [comment]
Thinking about this more, there are some cases where you want to perform an action unconditionally, e.g. unsubscribing when your own context is cancelled. So, I think we need versions of the functions that don't take a context was well. I'll add this.

**Comment by twpayne** [comment]
Done in c208475265b8b9eeb1b74d1514edadf7a1074715.
